version: '3.9'

name:
  bankBaseCluster

volumes:
  mongo_data:

networks:
  appNetwork:
    external: true
    driver: bridge

services:
  mongo:
    image: mongo:noble
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - '27017:27017'

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - '8081:8081'
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_URL: mongodb://root:root@mongo:27017/
      ME_CONFIG_BASICAUTH: false

  service:
    build:
      context: '../../../CoffeeBank/Apps/BankBase/backend'
      dockerfile: Dockerfile
    ports:
      - '127.0.0.1:8080:8080'
    environment:
      SPRING_DATASOURCE_URL: 'jdbc:postgresql://database:5432/CoffeeBank'
    networks:
      - appNetwork