version: '3.9'

name:
  bankBusinessCluster

networks:
  appNetwork:
    external: true
    driver: bridge

services:
  service:
    build:
      context: '../../../CoffeeBank/Apps/BankBusiness/backend'
      dockerfile: Dockerfile
    ports:
      - '1337:1337'
    networks:
      - appNetwork