spring:
  application:
    name: emailConfirmationService
  kafka:
    consumer:
      group-id: 'emailConfirmationServiceConsumers'
      bootstrap-servers: 'localhost:59092'
    producer:
      bootstrap-servers: 'localhost:59092'
  data:
    mongodb:
      database: emailConfirmationRequests
      host: 'localhost'
      port: 27017
      username: root
      password: root
      authentication-database: admin