version: '3.9'

volumes:
  pg_data:

services:
  db:
    image: postgres:16.3-alpine
    restart: always
    environment:
      POSTGRES_DB: CoffeeBank
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    expose:
      - 5432
    ports:
      - '5433:5432'
    volumes:
#      - ./src/main/resources/sql/create.sql:/docker-entrypoint-initdb.d/001.sql
#      - ./src/main/resources/sql/insert.sql:/docker-entrypoint-initdb.d/002.sql
      - pg_data:/var/lib/postgresql/data
    hostname: database
    deploy:
      resources:
        limits:
          memory: 500MB
        reservations:
          memory: 500MB
