server {
  port: 1338
}

kafka {
  bootstrap-servers = "localhost:59092"
  group-id = "mail-sender-consumer"
  consumer-topic = "client_email-confirmation-topic"
  producer-topic = "client_confirmation_email_response-topic"
}

mongo {
  username = "root"
  password = "root"
  host = "localhost"
  port = 27017
  authentication-database = "admin"
  database = "email-confirm"
  collection = "EmailConfirmation"
}

emailing {
  host = "smtp.gmail.com"
  port = 465
  auth = true
  ssl-enable = true
  username = "CoffeeBankMailer@gmail.com"
  password = "xose hnmq hrgw mcpu"
  sender = "CoffeeBank@noreply.ru"
}
