application {
  grpc {
    address = "localhost"
    port = 9090
  }
  kafka {
    main.consumer {
        bootstrap-servers = "localhost:29092, localhost:39092, localhost:49092"
        group-id = "main-core-consumers"
    }
    util {
      producer {
        bootstrap-servers = "localhost:59092"
        group-id = "util-core-producers"
      }
      consumer {
        bootstrap-servers = "localhost:59092"
        group-id = "util-core-consumers"
      }
    }
  }
  postgres {
    host = "localhost"
    port = 5433
    username = "postgres"
    password = "postgres"
    database = "CoffeeBank"
  }
}