spring:
  application:
    name: backend
  datasource:
    url: jdbc:postgresql://localhost:5433/CoffeeBank
    username: postgres
    password: postgres
  jpa:
    properties.hibernate:
      show_sql: true
      format_sql: true
    hibernate:
      ddl-auto: none
  #    hibernate:
#      ddl-auto: validate
  kafka:
    main:
      consumer:
        bootstrap-servers: "localhost:29092, localhost:39092, localhost:49092"
        group-id: "main-core-consumers"
    util:
      producer:
        bootstrap-servers: "localhost:59092"
        group-id: "util-core-producers"
      consumer:
        bootstrap-servers: "localhost:59092"
        group-id: "util-core-consumers"
#      properties:
#        spring.json.trusted.packages: "org.d3javu.backend.kafka.requests.account"
#      isolation-level: read_uncommitted
logging:
  level:
    org.apache.kafka.clients.NetworkClient: error
springdoc:
  swagger-ui:
    path: /swagger-ui/index.html
server:
  port: 28080
grpc:
  server:
    port: 9090
    ssl:
      secure: false
      enabled: false
