application {
  grpc {
    address = "localhost"
    port = 9090
  }
  kafka {
    main{
        consumer {
            bootstrap-servers = "localhost:29092,localhost:39092,localhost:49092"
            group-id = "main-core-consumers"
        }
        base-topics {
            account-create = "account-create-topic"
            account-rename = "account-rename-topic"
            card-create = "card-create-topic"
            card-rename = "card-rename-topic"
            client-registration = "client-registration-topic"
        }
        business-topics {
            client-registration = "business-client_registration_topic"
            payment-account-create = "payment-account_create_topic"
            contact-person-create = "contact-person_create_topic"
            contact-person-update = "contact-person_update_topic"
            contact-person-delete = "contact-person_delete_topic"
        }
    }
    util {
      producer {
        bootstrap-servers = "localhost:59092"
        group-id = "util-core-producers"
      }
      consumer {
        bootstrap-servers = "localhost:59092"
        group-id = "util-core-consumers"
      }
      request-topic = "client_email-confirmation-topic"
      response-topic = "client_confirmation_email_response-topic"
    }
  }
  postgres {
    host = "localhost"
    port = 5433
    username = "postgres"
    password = "postgres"
    database = "CoffeeBank"
  }
}